#!/bin/sh
cd "$( dirname "${BASH_SOURCE[0]}" )"
./wp.sh search-replace '//ap.washington.edu' '//{{wordpress_webdomain}}' --all-tables --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh user create simtest1 simtest1@uw.edu --user_pass=u5miwt10iaz8yxrtxjts --role=administrator --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh user create simtest2 simtest2@uw.edu --user_pass=jyjz0erqjzaljneox02a --role=editor --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh user create simtest3 simtest3@uw.edu --user_pass=zttw5s7iy5x2bfi3u4z2 --role=subscriber --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace acadvisa@u testvisa@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace acadsim@u testsim@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace acadpim@u testpim@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace acadpt@u testpt@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace eoaa@u testeoaa@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace acadpers@u testpers@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace acadhr@u  testhr@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace vpap@u testsim@u  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace 'acadvisa@u' 'testvisa@u'  wp_ap_frm_forms  wp_ap_frm_fields   wp_ap_frm_item_metas wp_ap_frm_items  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace 'acadsim@u' 'testsim@u'  wp_ap_frm_forms  wp_ap_frm_fields   wp_ap_frm_item_metas  wp_ap_frm_items  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace 'eoaa@u' 'testeoaa@u'  wp_ap_frm_forms  wp_ap_frm_fields   wp_ap_frm_item_metas  wp_ap_frm_items  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace 'acadpers@u' 'testpers@u'  wp_ap_frm_forms  wp_ap_frm_fields   wp_ap_frm_item_metas  wp_ap_frm_items  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace 'acadhr@u'  'testhr@u'  wp_ap_frm_forms  wp_ap_frm_fields   wp_ap_frm_item_metas  wp_ap_frm_items  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh search-replace 'UA-43909085-1' 'UA-43909085-2'  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh plugin deactivate  swiftype  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh plugin deactivate  google-analytics-for-wordpress  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh plugin list  --path='{{wordpress_dir}}/{{wordpress_webroot}}'
./wp.sh option set --path='{{wordpress_dir}}/{{wordpress_webroot}}' blogname 'Academic Personnel - {{shconfig_env_type}}'
./wp.sh option set --path='{{wordpress_dir}}/{{wordpress_webroot}}' ap_hiring_plan_notify_unit_admins no
